
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmzowktbkegdvnfinktm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tem93a3Ria2VnZHZuZmlua3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDEzNDUsImV4cCI6MjA2MzM3NzM0NX0.dWz1GT4Dtd4O37w-vbpX36yZlnn_l2NTuPIA2Onw0YY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
